name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - r-base
  - plotly
  - pandas
  - matplotlib
  - scikit-learn
  - numpy
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - r-seurat
  - r-devtools
<<<<<<< HEAD
  - bioconductor-biomart
=======
  - r-biomartr=3.17
>>>>>>> db85f9be758312f8eafd2e2654e4434631ac9ae4
  
  
