name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - r-base
  - plotly
  - pandas
  - matplotlib
  - scikit-learn
  - numpy
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - r-seurat
  - r-devtools
  - bioconductor-biomart
  - r-ggVennDiagram
  - r-readxl
  - r-sf
  
  
